<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <PbTargetFramework Condition="'$(PbTargetFramework)' == ''">net8.0</PbTargetFramework>
    <OrchardCoreVersion Condition="'$(OrchardCoreVersion)' == ''">2.2.1</OrchardCoreVersion>
    <TargetFramework>$(PbTargetFramework)</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
	  <PackageId>PropertyBrokersDigital.OrchardCore.WorkflowAdditions</PackageId>
	  <RepositoryType>git</RepositoryType>
	  <RepositoryUrl>https://github.com/PropertyBrokersDigital/PropertyBrokers.OrchardCore.WorkflowAdditions</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

	<ItemGroup>
	  <Folder Include="Abstractions\" />
	  <Folder Include="Models\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="NETCore.MailKit" Version="2.1.0" />
		<PackageReference Include="Newtonsoft.Json.Schema" Version="4.0.1" />
		<PackageReference Include="OrchardCore.Module.Targets" Version="$(OrchardCoreVersion)" />
		<PackageReference Include="OrchardCore.Contents" Version="$(OrchardCoreVersion)" />
		<PackageReference Include="OrchardCore.Email" Version="$(OrchardCoreVersion)" />
		<PackageReference Include="OrchardCore.Queries" Version="$(OrchardCoreVersion)" />
		<PackageReference Include="OrchardCore.Users" Version="$(OrchardCoreVersion)" />
		<PackageReference Include="OrchardCore.Workflows" Version="$(OrchardCoreVersion)" />
		<PackageReference Include="OrchardCore.ContentManagement" Version="$(OrchardCoreVersion)" />
		<PackageReference Include="OrchardCore.Data.Abstractions" Version="$(OrchardCoreVersion)" />
		<PackageReference Include="OrchardCore.Data.YesSql.Abstractions" Version="$(OrchardCoreVersion)" />
		<PackageReference Include="OrchardCore.DisplayManagement" Version="$(OrchardCoreVersion)" />
		<PackageReference Include="OrchardCore.Media.Abstractions" Version="$(OrchardCoreVersion)" />
		<PackageReference Include="OrchardCore.Search.AzureAI.Core" Version="$(OrchardCoreVersion)" Condition="'$(PbTargetFramework)' != 'net10.0'" />
		<PackageReference Include="OrchardCore.AzureAI.Core" Version="$(OrchardCoreVersion)" Condition="'$(PbTargetFramework)' == 'net10.0'" />
		<PackageReference Include="PropertyBrokersDigital.Email" Version="1.0.1" />
    	<PackageReference Include="PropertyBrokersDigital.Email.Graph" Version="1.1.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\PropertyBrokers.OrchardCore.ContentTypeAdditions\PropertyBrokers.OrchardCore.EmailTemplating\PropertyBrokers.OrchardCore.EmailTemplating.csproj" />
	</ItemGroup>
</Project>
